created the initial components
JessicaDSL/pokeProject pull request #1
Opened 2021-09-01 20:07 UTC by JessicaDSL

2021-09-05 19:02 UTC, RonaldoSetzer commented on package.json
> +    "react-router-dom": "^5.2.1",
Pq vc comitou o react router nesse PR se ele nao sera usado agora?

2021-09-05 19:02 UTC, RonaldoSetzer commented on src/components/Header/Header.js
> +    <Component>
Nao entendi o pq dessa div dentro da outro e o porque desses nomes `Component` e`Head`

2021-09-08 02:05 UTC, RonaldoSetzer requested changes

2021-09-08 02:05 UTC, RonaldoSetzer commented on src/components/ListPokeSection/ListPokeSection.js
> +  function verifyId(item) {
- Esse metodo e melhor jogar para dentro de um arquivo utils
```src/utils/index.js```
- Ao invez de pegar um item como paretro, coloca para receber apenas um numero
- Esse nome nao faz muito sentido, pq vc nao esta verificando nada, vc esta adicionadno zero a esquerda
- Por hora esses `ifs` funcionam, mas num futuro iremos mudar esse algoritimo para algo utilizando loops

2021-09-08 02:05 UTC, RonaldoSetzer commented on src/components/ListPokeSection/ListPokeSection.js
> +              <PokeOption key={key}>
- Nao entendi o nome PokeOption.
- Ao invez de usar o StyledComponent, e melhor vc criar um componente isolado chamdo PokeCard, e esse componente tem q estar no storybook tb

2021-09-08 02:05 UTC, RonaldoSetzer commented on src/components/ListPokeSection/content.js
> +export const list = [
esse content.js nao faz sentido a existencia dele, o que voce fez aqui, deveria ficar dentro do arquivo do storybook, lembrando e o storybook que mostra os exemplos funcionando

2021-09-08 14:15 UTC, JessicaDSL commented on package.json
> +    "react-router-dom": "^5.2.1",
Quando ele foi implementado eu já estava seguindo as lista de tarefa, foi erro na parte de entender o passo a passo

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/Foooter/Footer.js
> +    <Component>
Nao use `Component`, Utilize `Container` ou `Background` caso tenha alguma cor

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/Foooter/Footer.js
> +      {numberPage.map((item, key) => {
- `NumberList` nao faz sentido, afinal esse estilo so esta colocando cor no icon
- nao tinha necessidade de colocar numa variavel dentro de content ja que e algo fixo e nao e texto, e como e so 3 nem precisa colocar em loop

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/Foooter/content.js
> +import FavoriteIcon from '@material-ui/icons/Favorite';
esse arquivo nao precisa existir

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/Foooter/styles.js
> +export const NumberList = styled.div`
como falei antes, esse NumberList nao faz sentido ^^

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/Header/Header.js
> +    <Component>
Esse nome Head continua a nao fazer sentido

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/ListPokeSection/ListPokeSection.js
> +import { Section, PokeSection } from "./styles";
Esses nomes tambem nao fazem sentido, tem que ser mais coerente com o que cada classe representa

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/ListPokeSection/ListPokeSection.js
> +           <PokeCard />
Aqui sim deveria ter um loop, percorrendo uma lista e criando um Pokecard com as informacoes da lista

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/PokeCard/PokeCard.js
> +      {cardInfo.map((item, key) => {
nao entendi o pq desse card info, essas informacoes deveriam vir como parametro, e o pq vc fez um map aqui?

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/PokeCard/PokeCard.js
> +import { verifyId } from "../../utils/utils";
Pense num outro nome verifyId nao faz sentido, sei la ```formatPokeId```

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/TeamSection/TeamSection.js
> +        <ul>
aqui vc precisa pegar a lista via parametro e fazer um loop

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/PokeCard/content.js
> +export const cardInfo = [
nao etendi pq colocou dentro de um array

2021-09-10 14:13 UTC, RonaldoSetzer commented on src/components/PokeCard/content.js
> +    ids: 167,
pq ids esta no plural

2021-09-10 14:19 UTC, JessicaDSL commented on src/components/PokeCard/content.js
> +    ids: 167,
Pq fiquei preocupada de ter dado conflitos, já foi corrigido.

2021-09-10 14:20 UTC, JessicaDSL commented on src/components/PokeCard/content.js
> +export const cardInfo = [
pois primeiramente se tratava de um array, para organizar o grid, mas já foi corrigido, obrigada

2021-09-10 14:44 UTC, JessicaDSL commented on src/components/TeamSection/TeamSection.js
> +        <ul>
Corrigido

2021-09-10 14:47 UTC, JessicaDSL commented on src/components/PokeCard/PokeCard.js
> +import { verifyId } from "../../utils/utils";
Concordo que formatPokeId fez muito mais sentido, corrigido.

2021-09-10 18:47 UTC, JessicaDSL commented on src/components/PokeCard/PokeCard.js
> +      {cardInfo.map((item, key) => {
Foi realocado o map

2021-09-10 18:47 UTC, JessicaDSL commented on src/components/ListPokeSection/ListPokeSection.js
> +           <PokeCard />
Corrigido

2021-09-10 18:53 UTC, JessicaDSL commented on src/components/ListPokeSection/ListPokeSection.js
> +import { Section, PokeSection } from "./styles";
Foi corrigido, será analisado melhor posteriormente

2021-09-14 23:57 UTC, RonaldoSetzer requested changes
Ta quase, mas ta melhorando ^^

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/PokeCard/PokeCard.js
> +    <ListItem>
Apesar do PokeCard ser um ListItem, esse ```<ListItem>``` nao faz sentido ter esse nome, sua funcao e um ```Container``` ou ```Background```

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/PokeCard/PokeCard.js
> +/*<ListItem key={key}>
Nao deixe codigo comentado aleatoriamente, se nao for para explicar algo, e melhor deletar

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/PokeList/content.js
> +export const cardInfo = [
Esse arquivo nao precisa exister, provavelmente ja nao esta sendo mais usado.

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/PokeList/PokeList.js
> +//ai ta dando esse erro esquisito
comentario aleatorio no codigo

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/Team/styles.js
> +  h1 {
nao e um erro, mas eu particularmente gosto de pular uma linha entre os blocos para facilitar na leitura

2021-09-14 23:57 UTC, RonaldoSetzer commented on src/components/Team/Team.js
> +      <TeamList>
ja estamos dentro do componente Team, e so existe uma lista, entao acho que nao precisaria colocar ```<TeamList>``` so ```<List>``` ja representaria bem o proprosito

2021-09-15 13:05 UTC, JessicaDSL commented on src/components/PokeList/content.js
> +export const cardInfo = [
Corrigido.

2021-09-15 13:05 UTC, JessicaDSL commented on src/components/PokeCard/PokeCard.js
> +/*<ListItem key={key}>
Corrigido.

2021-09-15 13:05 UTC, JessicaDSL commented on src/components/PokeCard/PokeCard.js
> +    <ListItem>
Corrigido.

2021-09-15 13:13 UTC, RonaldoSetzer approved these changes
Boa 06 🙏 
LGTM 👍

2021-09-15 13:29 UTC, merged